Test-project/Test-project-web/src/main/java/fr/ensimag/Testproject/controler/person/AnnonceBean.java
package fr.ensimag.Testproject.controler.person;

import fr.ensimag.Testproject.Annonce;
import fr.ensimag.Testproject.User;
import fr.ensimag.Testproject.stateless.AnnonceFacadeLocal;
import fr.ensimag.Testproject.stateless.UserFacadeLocal;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import javax.servlet.http.HttpServletRequest;
/**
*
* @author reignier
*/
@Named(value = "annonceBean")
@RequestScoped
public class AnnonceBean {
    @EJB
    private AnnonceFacadeLocal annonceFacade;
    @EJB
    private UserFacadeLocal userFacade;
        
    private List<AnnonceSelected> annonces;
    private User user;

    public User getUser() {
        FacesContext context = FacesContext.getCurrentInstance();
        HttpServletRequest request = (HttpServletRequest) context.getExternalContext().getRequest();

        String email = request.getRemoteUser();
        user = userFacade.find(email);
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

  
    @PostConstruct
    public void init() {
        annonces = new ArrayList<>();
        for(Annonce a : annonceFacade.findAll()) {
            if (a.getEstDispo()) {
                AnnonceSelected ann = new AnnonceSelected(a, false);
                annonces.add(ann);
            }
        }
    }
    
    public List<AnnonceSelected> getAnnonces() {
        return annonces;
    }

/*
            <p:outputLabel value="Annonces disponibles" />
        <p:selectManyMenu value="#{annonceBean.selected}" showCheckbox="true" converter="annonceConverter" filter="true" filterMatchMode="contains">
            <f:selectItems value="#{annonceBean.annonces}" var="annonce" itemLabel="#{annonce.competence.name}" />

        </p:selectManyMenu>
    */
    public String buyAnnonces(){
        user = getUser();
        if ( user == null)
            System.out.println("erreur achat, utilisateur non connecté");
        else {
            List<Annonce> toBuy = new ArrayList<>();
            for(AnnonceSelected a : annonces) {
                if (a.getSelected()) {
                    toBuy.add(a.getAnnonce());
                }
            }
            try {
               userFacade.addAchetees(toBuy, user);
                // Success : enlever les annonces des annonces dispos
                annonceFacade.annoncesPlusDispo(toBuy);
            } catch (Exception ex) {
                Logger.getLogger(AnnonceBean.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        init();
        return "/secure/achatAnnonce.xhtml?faces-redirect=true";
    }

}

Test-project/Test-project-web/src/main/java/fr/ensimag/Testproject/controler/person/AuthenticationBean.java
package fr.ensimag.Testproject.controler.person;
 
import fr.ensimag.Testproject.stateless.UserFacadeLocal;
import javax.ejb.EJB;
import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.context.FacesContext;
import javax.faces.event.ComponentSystemEvent;
import javax.inject.Named;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;

@Named(value = "authentificationBean")
@RequestScoped
@ManagedBean
public class AuthenticationBean {
    @EJB
    private UserFacadeLocal userFacade;
    private String email;
    private String password;

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
    
    public boolean isConnected() {
        FacesContext context = FacesContext.getCurrentInstance();
        HttpServletRequest request = (HttpServletRequest) context.getExternalContext().getRequest();
        return request.getRemoteUser()!=null;
    }
    
    public void logIn() {
        FacesContext context = FacesContext.getCurrentInstance();
        HttpServletRequest request = (HttpServletRequest) context.getExternalContext().getRequest();
        if (!userFacade.isEmailExistant(email)) {
            System.out.println("Email inexistant");
            context.addMessage("loginForm:j_username", new FacesMessage("Erreur: identifiant inconnu"));
        } 
    }

    public void checkErrors(ComponentSystemEvent event) {
        FacesContext context = FacesContext.getCurrentInstance();
        HttpServletRequest request = (HttpServletRequest) context.getExternalContext().getRequest();
        if ("true".equals((String)request.getParameter("failed"))) {
            /* GET parameter "failed" has been sent in the HTTP request... */
            context.addMessage(null, new FacesMessage("Connexion échouée"));
        }
        else if (request.getRequestedSessionId()!=null && !request.isRequestedSessionIdValid()
                    & request.getParameter("logout")==null) {
            /* The user session has timed out (not caused by a logout action)... */
            context.addMessage(null, new FacesMessage("Your session has timed out!"));
        }
        else if (request.getParameter("logout")!=null && request.getParameter("logout").equalsIgnoreCase("true")) {
            context.addMessage(null, new FacesMessage("Déconnexion réussie"));
        } 
    }
    
    public String logout() {
        String page="/SignInUser?logout=true&faces-redirect=true";
        FacesContext context = FacesContext.getCurrentInstance();
        HttpServletRequest request = (HttpServletRequest) context.getExternalContext().getRequest();
        try {
          request.logout();
        } catch (ServletException e) {
            context.addMessage(null, new FacesMessage("Déconnexion échouée"));
            page="/SignInUser?logout=false&faces-redirect=true";
        }
        return page;
    }
}

Test-project/Test-project-web/src/main/java/fr/ensimag/Testproject/controler/person/CompetenceBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.ensimag.Testproject.controler.person;


import fr.ensimag.Testproject.Annonce;
import fr.ensimag.Testproject.Competence;
import fr.ensimag.Testproject.User;
import fr.ensimag.Testproject.stateless.AnnonceFacadeLocal;
import fr.ensimag.Testproject.stateless.CompetenceFacadeLocal;
import fr.ensimag.Testproject.stateless.UserFacadeLocal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import javax.servlet.http.HttpServletRequest;

/**
 *
 * @author tonnoira
 */
@ManagedBean
@SessionScoped
@Named(value = "competenceBean")
public class CompetenceBean {
    @EJB
    private CompetenceFacadeLocal competenceFacade;
    @EJB
    private AnnonceFacadeLocal annonceFacade;
    
    public List<Competence> competences;
    public String selectedCompetence;
    public boolean affiche;
    String Lieu;
    public List<Annonce> toPrint;
    
    @PostConstruct
    public void init(){
        System.out.println("bananaaaaa");
        competences = new ArrayList<>();
        toPrint = new ArrayList<>();
        for(Competence a : competenceFacade.findAll()) {
                competences.add(a);
        }        
        competences.add(new Competence("dev"));
        competences.add(new Competence("trade"));
        affiche = false;
    }
    
    public void update(){
        for(Competence a : competenceFacade.findAll()) {
            if(!competences.contains(a)){
                competences.add(a);
            }
        }
    }
         
    public List<Competence> getCompetences(){
        return competences;
    }
    
    public void setCompetences(List<Competence> comp){
        this.competences = comp;
    }
    
    public String getSelectedCompetence(){
        return selectedCompetence;
    }
    
    public void setSelectedCompetence(String s){
        this.selectedCompetence = s;
    }
    
    public boolean isShow(){
        return affiche;
    }
    
    public List<Annonce> getToPrint(){
        return toPrint;
    }
    
    public String recherche(){
        update();
        HttpServletRequest request = (HttpServletRequest)FacesContext.getCurrentInstance().getExternalContext().getRequest();
        String lieu = request.getParameter("lieu");
        this.Lieu = lieu;
        affiche = true;
        
        System.out.println("lieu " + lieu);
        toPrint.clear();
        for(Annonce a : annonceFacade.findAll()) {
            //System.out.println(a.getUser().getZipcode());
            //System.out.println(a.getCompetence().getName());
            if(lieu.equals("") || lieu.equals("Zipcode")){
                //System.out.println("lieu 0");
                if(a.getCompetence().getName().equals(selectedCompetence)){
                    //System.out.println("bonne comp");
                    toPrint.add(a);
                }                              
            }else{
                //System.out.println("lieu");
                //System.out.println(Integer.parseInt(lieu) + " " + a.getUser().getZipcode());
                if(a.getUser().getZipcode() == Integer.parseInt(lieu)){
                    //System.out.println("bon lieu");
                  if(a.getCompetence().getName().equals(selectedCompetence)){
                      //System.out.println("bonne comp");
                        toPrint.add(a);
                    }    
                }
            }
        }
        return "index.xhtml?faces-redirect=true";
    }
    
}

Test-project/Test-project-web/src/main/java/fr/ensimag/Testproject/controler/person/PanierBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.ensimag.Testproject.controler.person;

import fr.ensimag.Testproject.Annonce;
import fr.ensimag.Testproject.Competence;
import fr.ensimag.Testproject.User;
import fr.ensimag.Testproject.stateful.PanierFacade;
import fr.ensimag.Testproject.stateful.PanierFacadeLocal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

/**
 *
 * @author brenierr
 */
@ManagedBean
@SessionScoped // Ce controller est valable pour toute la session courante
public class PanierBean implements java.io.Serializable {
        
    /** Identifiant du dernier numéro d'article ajouter au panier dans la session */
    private Integer numeroLastArticle = 0;
    
    private static final String PANIER_BEAN_SESSION_KEY = "Panier";
    
    public Integer getNumeroLastArticle() {
        return numeroLastArticle;
    }

    /**
     * Fonction qui recupere une session à partir du faces context 
     */
    private PanierFacadeLocal getSession(){
        FacesContext context = FacesContext.getCurrentInstance();
        HttpServletRequest request = (HttpServletRequest) context.getExternalContext().getRequest();
        PanierFacadeLocal panier = (PanierFacadeLocal) request.getSession().getAttribute(PANIER_BEAN_SESSION_KEY);
        if ( panier == null) {
        //    try {
                //InitialContext ic = new InitialContext();
                
                //lookup                
                panier = new PanierFacade();  
                System.out.println("test test ");
                request.getSession().setAttribute(PANIER_BEAN_SESSION_KEY, panier);
                
        /*    } catch ( NamingException e) {
                throw new ServletException(e);
            }*/
        }
        return panier;
    }


    
    /** 
     * Fonction qui permet de recuperer l'age dans la session 
     * @return l'age 
     */
    public List<Annonce> getArticles(){
        PanierFacadeLocal panier = getSession();    
        return panier.getAnnonces();
    }
    
    // TODO : a enlever c'est que pour les tests 
     
    @EJB
    private fr.ensimag.Testproject.stateless.UserFacadeLocal userFacade;
    @EJB
    private fr.ensimag.Testproject.stateless.CompetenceFacadeLocal competenceFacade;
    @EJB
    private fr.ensimag.Testproject.stateless.AnnonceFacadeLocal annonceFacade;

    public void addArticle() {
        System.out.println("test model 1" + annonceFacade.findAll().size());
        if (numeroLastArticle==0) {
            char[] password = "azerty".toCharArray();
            User p = new User("duzaeapond", "jean", password,"brenier5@", 0, 27932, "01/01/2012");
            userFacade.create(p);


            PanierFacadeLocal panier = getSession();
            Competence c = new Competence("maths");
            competenceFacade.create(c);
            Date date = new Date();
            Integer heure = 1;       
            Annonce annonce = new Annonce(c,p,date,heure);
            annonceFacade.create(annonce);       
            panier.addAnnonce(annonce);


            c= new Competence("fr");
            competenceFacade.create(c);
            annonce = new Annonce(c,p,date,heure);
            annonceFacade.create(annonce);

            System.out.println("test model " + annonceFacade.findAll().size());
            panier.addAnnonce(annonce);
        } else {
            char[] password = "azerty".toCharArray();
            User p = new User("duzaeapond", "jean", password,"brenier6@", 0, 27932, "01/01/2012");
            userFacade.create(p);


            PanierFacadeLocal panier = getSession();
            Competence c = new Competence("maths2");
            competenceFacade.create(c);
            Date date = new Date();
            Integer heure = 1;       
            Annonce annonce = new Annonce(c,p,date,heure);
            annonceFacade.create(annonce);       
            panier.addAnnonce(annonce);


            c= new Competence("fr2");
            competenceFacade.create(c);
            annonce = new Annonce(c,p,date,heure);
            annonceFacade.create(annonce);

            System.out.println("test model " + annonceFacade.findAll().size());
            panier.addAnnonce(annonce);
        }
        numeroLastArticle++;
        
    }
    
    public Integer getArticlesSize() {
        System.out.println("size dans getArticles" + getArticles().size());
        return getArticles().size();
    }
}

Test-project/Test-project-web/src/main/webapp/FAQ.xhtml
<?xml version='1.0' encoding='UTF-8' ?> 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui">

    <h:head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <link rel="stylesheet" type="text/css" href="resources/css/cssLayout.css"/>   
        <link rel="stylesheet" type="text/css" href="resources/css/default.css"/>
        <link rel="stylesheet" href="resources/css/bootstrap.css" type="text/css"/>
        <link rel="stylesheet" href="resources/css/bootstrap-theme.css" type="text/css"/>
        <title>Facelets Template</title>
    </h:head>

    <ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                    template="./templateNotLogged.xhtml">
        <ui:define name="content">
            
            <h1 class="text-center">FAQ</h1>
            
                       <br> </br> <br> </br>
            <h4 class="text-center"> Question 1 : Est ce que <b>Bzous.com</b> c'est payant ?</h4>
            <h4 class="text-center" style="color:#F9429E"> Non ! <b>Bzou</b> est GRATUIT et le restera toujours pour tous les <b>Bzouteurs</b> !</h4>

            <br> </br>

            <h4 class="text-center"> Question 2 : Je n'ai plus aucun <b>Bzou</b> comment puis je faire pour continuer à prendre des cours ?</h4>
            <h4 class="text-center" style="color:#F9429E"> Ne t'inquiète pas ! Il te suffit de partager à ton tour tes savoirs et compétences, très rapidement tu auras plein de <b>Bzous</b> et de nouveaux <b>Bzouteurs</b> à ton carnet d'adresse !</h4>

            <br> </br>
            
            <h4 class="text-center"> Question 3 : D'autres questions ?</h4>
            <h4 class="text-center" style="color:#F9429E"> Envoie nous un mail à <b>Bzou@gmail.com</b> : tu auras des réponses... Et des <b>Bzous</b> bien sur ! ;)</h4>

            
            

            
        </ui:define>
    </ui:composition>

</html>

Test-project/Test-project-web/src/main/webapp/ListeCours.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">
    <ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                    template="./templateNotLogged.xhtml">
        <ui:define name="content">
            <f:event listener="#{authenticationBean.checkErrors}" type="preRenderView"/>
            <h:messages globalOnly="true"/>
            <div class="container">
                <div class='row'>
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <h3 class="panel-title"> <center>Ma Liste de Cours</center></h3>

                        </div>

                        <div class="panel-body"> 
                            <div class="col-md-12">

                                <h:body>

                                    <f:view>

                                        <table class="table-bordered table" id="Cours à donner : ">
                                            <table class="table" border="1">
                                                <thead>
                                                    <tr class="success">
                                                    <th>Cours à donner</th>
                                                    <th>à</th>
                                                    <th>Date</th>
                                                    <th>Heure</th>
                                                    </tr>
                                                </thead>
                                                
                                                <tbody>
                                                   <tr class="success">
                                                    <td>Matière 1</td>
                                                    <td> Nom1 Prénom1</td>
                                                    <td> Date1</td>
                                                    <td> Heure1</td>
                                                   </tr>
                                             
                                                </tbody>
                                              <tr class="success">
                                                
                                                    <td>Matière 2</td>
                                                    <td> Nom2 Prénom2</td>
                                                    <td> Date 2</td>
                                                    <td> Heure 2</td>
                                     
                                          </tr>
                                            </table>
                                             </table>
                                     



                                        <table class="table-bordered table" id="Cours à recevoir : ">
                                            <table class="table" border="1">
                                                <thead>
                                                    <tr class="danger">
                                                    <th>Cours à recevoir</th>
                                                    <th>à</th>
                                                    <th>Date</th>
                                                    <th>Heure</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <tr class="danger">
                                                    <td>Matière 3</td>
                                                    <td> Nom3 Prénom3</td>
                                                    <td> Date3</td>
                                                    <td> Heure3</td>
                                                    </tr>
                                                    <tr class="danger">
                                                        <td>Matière 4</td>
                                                        <td> Nom4 Prénom4</td>
                                                        <td> Date 4</td>
                                                        <td> Heure 4</td>
                                                    </tr>
                                                </tbody>

                                            </table>
                                        </table> 

                                        <h:form id="retourAcceuil">
                                            <p:commandButton value="Retour Accueil" action="#{registerUser.retourAccueil}" validateClient="true" class="btn btn-info" />
                                        </h:form>


                                    </f:view>
                                </h:body>
                            </div>
                        </div>
                    </div> 
                </div>
            </div>
        </ui:define>
    </ui:composition>
</html>

Test-project/Test-project-web/src/main/webapp/SignInUserError.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>TODO supply a title</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>
    <body>
        <div>Nom d'utilisateur ou mot de passe invalide</div>
    </body>
</html>

Test-project/Test-project-web/src/main/webapp/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">z
    <ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                    template="./templateNotLogged.xhtml">
        <ui:define name="content">
            <h:panelGroup rendered="#{competenceBean.show}" >
                <h:form id="describe">
                    <p:dataGrid value='#{competenceBean.toPrint}' var='annonce' columns="1">
                        <div class="container">
                            <div class='row'>
                                <div class="panel panel-primary">
                                    <div class="panel-body">
                                        <div class='row'>
                                            <div class="col-md-4">
                                                <h:outputText value='#{annonce.user.firstname}' />
                                            </div>
                                            <div class="col-md-4">
                                                <h:outputText value='#{annonce.user.name}'/>
                                            </div>
                                            <div class="col-md-4">
                                                <h:outputText value='#{annonce.user.birthdate}'/>
                                            </div>
                                            <div class='row'>
                                                <p:dataGrid value='#{annonce.user.disponibilites}' var='disponibilite' columns="1">
                                                    <h:outputText value='#{disponibilite.date}'/>
                                                </p:dataGrid>
                                            </div>   
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </p:dataGrid>
                </h:form>
            </h:panelGroup>
        </ui:define>
    </ui:composition>
</html>

Test-project/Test-project-web/src/main/webapp/mainPage.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./templateNotLogged.xhtml">

    <ui:define name="content">
        content
    </ui:define>

</ui:composition>

Test-project/Test-project-web/src/main/webapp/templateNotLogged.xhtml
<?xml version='1.0' encoding='UTF-8' ?> 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <h:head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <link rel="stylesheet" type="text/css" href="resources/css/cssLayout.css"/>   
        <link rel="stylesheet" type="text/css" href="resources/css/default.css"/>
        <link rel="stylesheet" href="resources/css/bootstrap.css" type="text/css"/>
        <link rel="stylesheet" href="resources/css/bootstrap-theme.css" type="text/css"/>
        <title>Facelets Template</title>
    </h:head>

    <h:body>
        <div id="wrapper">
            <header id="top">
                <img src="images/BzousLogoMini.jpg" alt="Logo"/>
                <table class="liensEntete"> 
                    <tr>
                        <h:panelGroup rendered="#{!authenticationBean.connected}">
                            <td class="column"><a href="registerUser.xhtml" class="myButton" style="height:30%">s'enregistrer</a></td>
                            <td class="column"><a href="SignInUser.xhtml" class="myButton" style="height:30%">se connecter</a></td>
                        </h:panelGroup>
                        <h:panelGroup rendered="#{authenticationBean.connected}">
                            <td class="column"><a href="MonProfil.xhtml" class="myButton"> Mon profil </a></td>
                            <td class="column">
                                <h:form class="myButton">
                                    <h:commandLink action="#{authenticationBean.logout}">Se déconnecter</h:commandLink>
                                </h:form>
                            </td>
                        </h:panelGroup>
                    </tr>
                    <tr>
                        <td class="column"></td>
                        <h:panelGroup rendered="#{authenticationBean.connected}">
                            <td class="column"><a href="index.xhtml" class="myButton">Mon panier</a></td>
                        </h:panelGroup>
                    </tr>
                </table>

                <div class="barreRecherche">
                    <table class="liensRecherche">
                        <tr>
                            <td style="position:absolute;width:10%">Je recherche une competence</td>
                            <td style="position:absolute;width:50%;left:10%">
                                <h:form style="display:inline-block">
                                    <h:selectOneListbox value="#{competenceBean.selectedCompetence}" size="1" id="competences" class="menu-deroulant">
                                        <f:selectItems value="#{competenceBean.competences}" var="competence"
                                                       itemValue="#{competence.name}" itemLabel="#{competence.name}"/>
                                    </h:selectOneListbox>


                                    <input class="text-primary" style="display:inline-block;width:100%" type="text" name="lieu" id="lieu" value="Zipcode"></input>

                                    <h:commandButton value="recherche" class="bouttonMenuDeroulant" style="position:absolute;left:65%" action="#{competenceBean.recherche}"></h:commandButton>
                                </h:form>
                            </td>

                            <td style="position:absolute;width:20%;left:68%;">
                                <a href="PresentBzous.xhtml" class="bouttonBarreRecherche">Qu'est ce que Bzous.com?</a>
                            </td>
                            <td style="position:absolute;width:5%;left:91%">
                                <a href="FAQ.xhtml" class="bouttonBarreRecherche">FAQ</a>
                            </td>
                        </tr>
                    </table>
                </div>
            </header>

            <div id="content">
                <ui:insert name="content" >
                    bananaaaa!!!! 
                </ui:insert>
            </div>

            <div id="bottom">
                <li style="display:inline-block;padding-left:20px;padding-right:20px;"><a href="index.xhtml">Page principale</a></li>
                <li style="display:inline-block;padding-left:20px;padding-right:20px;"><a href="FAQ.xhtml">FAQ</a></li>
                <li style="display:inline-block;padding-left:20px;padding-right:20px;"><a href="MentionLegale.xhtml#">Mentions légales</a></li>
            </div>
        </div>
    </h:body>

</html>